name: Commits Multilinguagem

on:
  schedule:
    - cron: "0 6 * * *"    # Roda às 06:00 UTC (03:00 no Brasil)
    - cron: "0 14 * * *"   # Roda às 14:00 UTC (11:00 no Brasil)
    - cron: "0 22 * * *"   # Roda às 22:00 UTC (19:00 no Brasil)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Atualizar arquivos de várias linguagens
        run: |
          echo "# $(date)" >> ras.py

          git config user.name "Victor Pimenta"
          git config user.email "viktorpimenta2705@gmail.com"
          git add *
          git commit -m "🔄 Commit multilinguagem em $(date)"
          git push
